language: python

cache: pip

matrix:
    include:
        - os: linux
          python: "nightly"
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
        - os: osx
          language: generic

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update         ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install python3; fi
  - pip3 install -r requirements-tests.txt

script:
  - py.test --flake8 --cov=. --cov-report=term --timeout=10

after_success:
  - codecov
